version: "3.8"
services:
  app:
    build: .
    ports:
      - "8093:8093"
    env_file:
      - .env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: minimalnotepad
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d/

volumes:
  mariadb-data:
